// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCul4Kkfc6HthlIlLPwKjKkgc1R-VU6ZYc',
    appId: '1:281986992531:web:7d77a9420df5538c0b4066',
    messagingSenderId: '281986992531',
    projectId: 'authentication-60008',
    authDomain: 'authentication-60008.firebaseapp.com',
    storageBucket: 'authentication-60008.firebasestorage.app',
    measurementId: 'G-71HTQXYTZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6KN7clasMJ3g5haUAqRH_GOF6qyogxcc',
    appId: '1:281986992531:android:f8776077fb6b338a0b4066',
    messagingSenderId: '281986992531',
    projectId: 'authentication-60008',
    storageBucket: 'authentication-60008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD74m5GZjNOw_RjEVLIkXYTr9DDpyDEUDc',
    appId: '1:281986992531:ios:9517515332c643b50b4066',
    messagingSenderId: '281986992531',
    projectId: 'authentication-60008',
    storageBucket: 'authentication-60008.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD74m5GZjNOw_RjEVLIkXYTr9DDpyDEUDc',
    appId: '1:281986992531:ios:9517515332c643b50b4066',
    messagingSenderId: '281986992531',
    projectId: 'authentication-60008',
    storageBucket: 'authentication-60008.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCul4Kkfc6HthlIlLPwKjKkgc1R-VU6ZYc',
    appId: '1:281986992531:web:a3e0e0654b9acf5f0b4066',
    messagingSenderId: '281986992531',
    projectId: 'authentication-60008',
    authDomain: 'authentication-60008.firebaseapp.com',
    storageBucket: 'authentication-60008.firebasestorage.app',
    measurementId: 'G-MD13GK7MJ5',
  );

}